/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD.h"
#include "UART.h"
#include "rx_int.h"
#include "tx_int.h"
#include "TX_aliases.h"
#include "TX.h"
#include "ADC1.h"
#include "QuadDec_Motor.h"
#include "QuadDec_Motor_PVT.h"
#include "QuadDec_Shoulder.h"
#include "QuadDec_Shoulder_PVT.h"
#include "Clock_Enc_Motor.h"
#include "Clock_Enc_Shoulder.h"
#include "ADC1_In_aliases.h"
#include "ADC1_In.h"
#include "Motor_A_aliases.h"
#include "Motor_A.h"
#include "Motor_B_aliases.h"
#include "Motor_B.h"
#include "Shoulder_A_aliases.h"
#include "Shoulder_A.h"
#include "Shoulder_B_aliases.h"
#include "Shoulder_B.h"
#include "Shoulder_I_aliases.h"
#include "Shoulder_I.h"
#include "Clock_1.h"
#include "Clock_2.h"
#include "Counter_1.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "isr_2.h"
#include "isr_1.h"
#include "Clock_3.h"
#include "Clock_4.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "UART_IntClock.h"
#include "ADC1_IRQ.h"
#include "ADC1_theACLK.h"
#include "ADC1_Bypass_aliases.h"
#include "ADC1_Bypass.h"
#include "QuadDec_Motor_isr.h"
#include "QuadDec_Motor_Cnt16.h"
#include "QuadDec_Shoulder_isr.h"
#include "QuadDec_Shoulder_Cnt16.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

